name: generate animation

on:
  schedule:
    - cron: "0 */24 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg?color_snake=#185FA5&color_dots=#E6F1FB,#B5D4F4,#85B7EB,#378ADD,#185FA5
            dist/github-snake-dark.svg?color_snake=#7aa2f7&color_dots=#1a1b2e,#2d3f76,#3d59a1,#7aa2f7,#9ece6a&palette=github-dark

      - uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
